apiVersion: v1
kind: Service
metadata:
  name: aad-aws-sync
  namespace: $(kubernetes-namespace)
spec:
  ports:
  - name: external
    port: 8080
    targetPort: 8080
  selector:
    app: aad-aws-sync